import 'dart:ui';

import '../models/DistrictModel.dart';
import '../models/StateModel.dart';

class Constants{

  List<States> states = [
    States(name: "Andhra Pradesh", code: "AP"),
    States(name: "Arunachal Pradesh", code: "AR"),
    States(name: "Assam", code: "AS"),
    States(name: "Bihar", code: "BR"),
    States(name: "Chhattisgarh", code: "CG"),
    States(name: "Goa", code: "GA"),
    States(name: "Gujarat", code: "GJ"),
    States(name: "Haryana", code: "HR"),
    States(name: "Himachal Pradesh", code: "HP"),
    States(name: "Jammu and Kashmir", code: "JK"), // Union territory
    States(name: "Jharkhand", code: "JH"),
    States(name: "Karnataka", code: "KA"),
    States(name: "Kerala", code: "KL"),
    States(name: "Madhya Pradesh", code: "MP"),
    States(name: "Maharashtra", code: "MH"),
    States(name: "Manipur", code: "MN"),
    States(name: "Meghalaya", code: "ML"),
    States(name: "Mizoram", code: "MZ"),
    States(name: "Nagaland", code: "NL"),
    States(name: "Odisha", code: "OR"),
    States(name: "Punjab", code: "PB"),
    States(name: "Rajasthan", code: "RJ"),
    States(name: "Sikkim", code: "SK"),
    States(name: "Tamil Nadu", code: "TN"),
    States(name: "Telangana", code: "TG"),
    States(name: "Tripura", code: "TR"),
    States(name: "Uttarakhand", code: "UK"),
    States(name: "Uttar Pradesh", code: "UP"),
    States(name: "West Bengal", code: "WB"),
    States(name: "Andaman and Nicobar Islands", code: "AN"), // Union territory
    States(name: "Chandigarh", code: "CH"), // Union territory
    States(name: "Dadra and Nagar Haveli", code: "DN"), // Union territory
    States(name: "Daman and Diu", code: "DD"), // Union territory
    States(name: "Delhi", code: "DL"), // National Capital Territory
    States(name: "Lakshadweep", code: "LD"), // Union territory
  ];

  List<District> districts = [
    // Andhra Pradesh
    District(name: "Anantapur", code: "AN", state: "Andhra Pradesh"),
    District(name: "Chittoor", code: "CH", state: "Andhra Pradesh"),
    District(name: "East Godavari", code: "EG", state: "Andhra Pradesh"),
    District(name: "Guntur", code: "GU", state: "Andhra Pradesh"),
    District(name: "Krishna", code: "KR", state: "Andhra Pradesh"),
    District(name: "Kurnool", code: "KU", state: "Andhra Pradesh"),
    District(name: "Prakasam", code: "PR", state: "Andhra Pradesh"),
    District(name: "Sri Potti Sriramulu Nellore", code: "NE", state: "Andhra Pradesh"),
    District(name: "Srikakulam", code: "SR", state: "Andhra Pradesh"),
    District(name: "Visakhapatnam", code: "VS", state: "Andhra Pradesh"),
    District(name: "Vizianagaram", code: "VZ", state: "Andhra Pradesh"),
    District(name: "West Godavari", code: "WG", state: "Andhra Pradesh"),
    District(name: "YSR Kadapa", code: "KA", state: "Andhra Pradesh"),

    // Arunachal Pradesh
    District(name: "Tawang", code: "TA", state: "Arunachal Pradesh"),
    District(name: "West Kameng", code: "WK", state: "Arunachal Pradesh"),
    District(name: "East Kameng", code: "EK", state: "Arunachal Pradesh"),
    District(name: "Papum Pare", code: "PP", state: "Arunachal Pradesh"),
    District(name: "Kurung Kumey", code: "KK", state: "Arunachal Pradesh"),
    District(name: "Kra Daadi", code: "KD", state: "Arunachal Pradesh"),
    District(name: "Lower Subansiri", code: "LS", state: "Arunachal Pradesh"),
    District(name: "Upper Subansiri", code: "US", state: "Arunachal Pradesh"),
    District(name: "West Siang", code: "WS", state: "Arunachal Pradesh"),
    District(name: "East Siang", code: "ES", state: "Arunachal Pradesh"),
    District(name: "Siang", code: "SI", state: "Arunachal Pradesh"),
    District(name: "Upper Siang", code: "UP", state: "Arunachal Pradesh"),
    District(name: "Lower Siang", code: "LS", state: "Arunachal Pradesh"),
    District(name: "Lepa Rada", code: "LR", state: "Arunachal Pradesh"),
    District(name: "Shi Yomi", code: "SY", state: "Arunachal Pradesh"),
    District(name: "Lower Dibang Valley", code: "LD", state: "Arunachal Pradesh"),
    District(name: "Dibang Valley", code: "DV", state: "Arunachal Pradesh"),
    District(name: "Anjaw", code: "AN", state: "Arunachal Pradesh"),
    District(name: "Lohit", code: "LO", state: "Arunachal Pradesh"),
    District(name: "Namsai", code: "NA", state: "Arunachal Pradesh"),
    District(name: "Changlang", code: "CH", state: "Arunachal Pradesh"),
    District(name: "Tirap", code: "TI", state: "Arunachal Pradesh"),
    District(name: "Longding", code: "LO", state: "Arunachal Pradesh"),

    // Assam
    District(name: "Baksa", code: "BA", state: "Assam"),
    District(name: "Barpeta", code: "BR", state: "Assam"),
    District(name: "Biswanath", code: "BI", state: "Assam"),
    District(name: "Bongaigaon", code: "BO", state: "Assam"),
    District(name: "Cachar", code: "CA", state: "Assam"),
    District(name: "Charaideo", code: "CH", state: "Assam"),
    District(name: "Chirang", code: "CI", state: "Assam"),
    District(name: "Darrang", code: "DA", state: "Assam"),
    District(name: "Dhemaji", code: "DH", state: "Assam"),
    District(name: "Dhubri", code: "DU", state: "Assam"),
    District(name: "Dibrugarh", code: "DI", state: "Assam"),
    District(name: "Dima Hasao", code: "DH", state: "Assam"),
    District(name: "Goalpara", code: "GO", state: "Assam"),
    District(name: "Golaghat", code: "GL", state: "Assam"),
    District(name: "Hailakandi", code: "HA", state: "Assam"),
    District(name: "Hojai", code: "HO", state: "Assam"),
    District(name: "Jorhat", code: "JO", state: "Assam"),
    District(name: "Kamrup Metropolitan", code: "KM", state: "Assam"),
    District(name: "Kamrup Rural", code: "KR", state: "Assam"),
    District(name: "Karbi Anglong", code: "KA", state: "Assam"),
    District(name: "Karimganj", code: "KA", state: "Assam"),
    District(name: "Kokrajhar", code: "KO", state: "Assam"),
    District(name: "Lakhimpur", code: "LA", state: "Assam"),
    District(name: "Majuli", code: "MA", state: "Assam"),
    District(name: "Morigaon", code: "MO", state: "Assam"),
    District(name: "Nagaon", code: "NA", state: "Assam"),
    District(name: "Nalbari", code: "NL", state: "Assam"),
    District(name: "Sivasagar", code: "SI", state: "Assam"),
    District(name: "Sonitpur", code: "SO", state: "Assam"),
    District(name: "South Salmara-Mankachar", code: "SS", state: "Assam"),
    District(name: "Tinsukia", code: "TI", state: "Assam"),
    District(name: "Udalguri", code: "UD", state: "Assam"),
    District(name: "West Karbi Anglong", code: "WK", state: "Assam"),

    // Bihar
    District(name: "Araria", code: "AR", state: "Bihar"),
    District(name: "Arwal", code: "AR", state: "Bihar"),
    District(name: "Aurangabad", code: "AU", state: "Bihar"),
    District(name: "Banka", code: "BA", state: "Bihar"),
    District(name: "Begusarai", code: "BE", state: "Bihar"),
    District(name: "Bhagalpur", code: "BH", state: "Bihar"),
    District(name: "Bhojpur", code: "BO", state: "Bihar"),
    District(name: "Buxar", code: "BU", state: "Bihar"),
    District(name: "Darbhanga", code: "DA", state: "Bihar"),
    District(name: "East Champaran", code: "EC", state: "Bihar"),
    District(name: "Gaya", code: "GA", state: "Bihar"),
    District(name: "Gopalganj", code: "GO", state: "Bihar"),
    District(name: "Jamui", code: "JA", state: "Bihar"),
    District(name: "Jehanabad", code: "JE", state: "Bihar"),
    District(name: "Kaimur", code: "KA", state: "Bihar"),
    District(name: "Katihar", code: "KA", state: "Bihar"),
    District(name: "Khagaria", code: "KH", state: "Bihar"),
    District(name: "Kishanganj", code: "KI", state: "Bihar"),
    District(name: "Lakhisarai", code: "LA", state: "Bihar"),
    District(name: "Madhepura", code: "MA", state: "Bihar"),
    District(name: "Madhubani", code: "MD", state: "Bihar"),
    District(name: "Munger", code: "MU", state: "Bihar"),
    District(name: "Muzaffarpur", code: "MU", state: "Bihar"),
    District(name: "Nalanda", code: "NA", state: "Bihar"),
    District(name: "Nawada", code: "NA", state: "Bihar"),
    District(name: "Patna", code: "PA", state: "Bihar"),
    District(name: "Purnia", code: "PU", state: "Bihar"),
    District(name: "Rohtas", code: "RO", state: "Bihar"),
    District(name: "Saharsa", code: "SA", state: "Bihar"),
    District(name: "Samastipur", code: "SA", state: "Bihar"),
    District(name: "Saran", code: "SA", state: "Bihar"),
    District(name: "Sheikhpura", code: "SH", state: "Bihar"),
    District(name: "Sheohar", code: "SH", state: "Bihar"),
    District(name: "Sitamarhi", code: "SI", state: "Bihar"),
    District(name: "Siwan", code: "SI", state: "Bihar"),
    District(name: "Supaul", code: "SU", state: "Bihar"),
    District(name: "Vaishali", code: "VA", state: "Bihar"),
    District(name: "West Champaran", code: "WC", state: "Bihar"),

    // Chhattisgarh
    District(name: "Balod", code: "BA", state: "Chhattisgarh"),
    District(name: "Baloda Bazar", code: "BB", state: "Chhattisgarh"),
    District(name: "Balrampur", code: "BP", state: "Chhattisgarh"),
    District(name: "Bastar", code: "BA", state: "Chhattisgarh"),
    District(name: "Bemetara", code: "BE", state: "Chhattisgarh"),
    District(name: "Bijapur", code: "BI", state: "Chhattisgarh"),
    District(name: "Bilaspur", code: "BL", state: "Chhattisgarh"),
    District(name: "Dantewada", code: "DA", state: "Chhattisgarh"),
    District(name: "Dhamtari", code: "DH", state: "Chhattisgarh"),
    District(name: "Durg", code: "DU", state: "Chhattisgarh"),
    District(name: "Gariaband", code: "GA", state: "Chhattisgarh"),
    District(name: "Gaurela-Pendra-Marwahi", code: "GP", state: "Chhattisgarh"),
    District(name: "Janjgir-Champa", code: "JC", state: "Chhattisgarh"),
    District(name: "Jashpur", code: "JA", state: "Chhattisgarh"),
    District(name: "Kabirdham", code: "KA", state: "Chhattisgarh"),
    District(name: "Kanker", code: "KA", state: "Chhattisgarh"),
    District(name: "Kondagaon", code: "KO", state: "Chhattisgarh"),
    District(name: "Korba", code: "KO", state: "Chhattisgarh"),
    District(name: "Koriya", code: "KR", state: "Chhattisgarh"),
    District(name: "Mahasamund", code: "MA", state: "Chhattisgarh"),
    District(name: "Mungeli", code: "MU", state: "Chhattisgarh"),
    District(name: "Narayanpur", code: "NA", state: "Chhattisgarh"),
    District(name: "Raigarh", code: "RA", state: "Chhattisgarh"),
    District(name: "Raipur", code: "RA", state: "Chhattisgarh"),
    District(name: "Rajnandgaon", code: "RA", state: "Chhattisgarh"),
    District(name: "Sukma", code: "SU", state: "Chhattisgarh"),
    District(name: "Surajpur", code: "SU", state: "Chhattisgarh"),
    District(name: "Surguja", code: "SU", state: "Chhattisgarh"),

    // Goa
    District(name: "North Goa", code: "NG", state: "Goa"),
    District(name: "South Goa", code: "SG", state: "Goa"),

    // Gujarat
    District(name: "Ahmedabad", code: "AH", state: "Gujarat"),
    District(name: "Amreli", code: "AM", state: "Gujarat"),
    District(name: "Anand", code: "AN", state: "Gujarat"),
    District(name: "Aravalli", code: "AR", state: "Gujarat"),
    District(name: "Banaskantha", code: "BA", state: "Gujarat"),
    District(name: "Bharuch", code: "BH", state: "Gujarat"),
    District(name: "Bhavnagar", code: "BH", state: "Gujarat"),
    District(name: "Botad", code: "BO", state: "Gujarat"),
    District(name: "Chhota Udaipur", code: "CU", state: "Gujarat"),
    District(name: "Dahod", code: "DA", state: "Gujarat"),
    District(name: "Dang", code: "DA", state: "Gujarat"),
    District(name: "Devbhoomi Dwarka", code: "DD", state: "Gujarat"),
    District(name: "Gandhinagar", code: "GA", state: "Gujarat"),
    District(name: "Gir Somnath", code: "GS", state: "Gujarat"),
    District(name: "Jamnagar", code: "JA", state: "Gujarat"),
    District(name: "Junagadh", code: "JU", state: "Gujarat"),
    District(name: "Kheda", code: "KH", state: "Gujarat"),
    District(name: "Kutch", code: "KU", state: "Gujarat"),
    District(name: "Mahisagar", code: "MA", state: "Gujarat"),
    District(name: "Mehsana", code: "ME", state: "Gujarat"),
    District(name: "Morbi", code: "MO", state: "Gujarat"),
    District(name: "Narmada", code: "NA", state: "Gujarat"),
    District(name: "Navsari", code: "NA", state: "Gujarat"),
    District(name: "Panchmahal", code: "PA", state: "Gujarat"),
    District(name: "Patan", code: "PA", state: "Gujarat"),
    District(name: "Porbandar", code: "PO", state: "Gujarat"),
    District(name: "Rajkot", code: "RA", state: "Gujarat"),
    District(name: "Sabarkantha", code: "SA", state: "Gujarat"),
    District(name: "Surat", code: "SU", state: "Gujarat"),
    District(name: "Surendranagar", code: "SU", state: "Gujarat"),
    District(name: "Tapi", code: "TA", state: "Gujarat"),
    District(name: "Vadodara", code: "VA", state: "Gujarat"),
    District(name: "Valsad", code: "VA", state: "Gujarat"),

    // Haryana
    District(name: "Ambala", code: "AM", state: "Haryana"),
    District(name: "Bhiwani", code: "BH", state: "Haryana"),
    District(name: "Charkhi Dadri", code: "CD", state: "Haryana"),
    District(name: "Faridabad", code: "FA", state: "Haryana"),
    District(name: "Fatehabad", code: "FA", state: "Haryana"),
    District(name: "Gurugram", code: "GU", state: "Haryana"),
    District(name: "Hisar", code: "HI", state: "Haryana"),
    District(name: "Jhajjar", code: "JH", state: "Haryana"),
    District(name: "Jind", code: "JI", state: "Haryana"),
    District(name: "Kaithal", code: "KA", state: "Haryana"),
    District(name: "Karnal", code: "KA", state: "Haryana"),
    District(name: "Kurukshetra", code: "KU", state: "Haryana"),
    District(name: "Mahendragarh", code: "MA", state: "Haryana"),
    District(name: "Nuh", code: "NU", state: "Haryana"),
    District(name: "Palwal", code: "PA", state: "Haryana"),
    District(name: "Panchkula", code: "PA", state: "Haryana"),
    District(name: "Panipat", code: "PA", state: "Haryana"),
    District(name: "Rewari", code: "RE", state: "Haryana"),
    District(name: "Rohtak", code: "RO", state: "Haryana"),
    District(name: "Sirsa", code: "SI", state: "Haryana"),
    District(name: "Sonipat", code: "SO", state: "Haryana"),
    District(name: "Yamunanagar", code: "YA", state: "Haryana"),

    // Himachal Pradesh
    District(name: "Bilaspur", code: "BI", state: "Himachal Pradesh"),
    District(name: "Chamba", code: "CH", state: "Himachal Pradesh"),
    District(name: "Hamirpur", code: "HA", state: "Himachal Pradesh"),
    District(name: "Kangra", code: "KA", state: "Himachal Pradesh"),
    District(name: "Kinnaur", code: "KI", state: "Himachal Pradesh"),
    District(name: "Kullu", code: "KU", state: "Himachal Pradesh"),
    District(name: "Lahaul and Spiti", code: "LS", state: "Himachal Pradesh"),
    District(name: "Mandi", code: "MA", state: "Himachal Pradesh"),
    District(name: "Shimla", code: "SH", state: "Himachal Pradesh"),
    District(name: "Sirmaur", code: "SI", state: "Himachal Pradesh"),
    District(name: "Solan", code: "SO", state: "Himachal Pradesh"),
    District(name: "Una", code: "UN", state: "Himachal Pradesh"),

    // Jammu and Kashmir
    District(name: "Anantnag", code: "AN", state: "Jammu and Kashmir"),
    District(name: "Bandipora", code: "BA", state: "Jammu and Kashmir"),
    District(name: "Baramulla", code: "BA", state: "Jammu and Kashmir"),
    District(name: "Budgam", code: "BU", state: "Jammu and Kashmir"),
    District(name: "Doda", code: "DO", state: "Jammu and Kashmir"),
    District(name: "Ganderbal", code: "GA", state: "Jammu and Kashmir"),
    District(name: "Jammu", code: "JA", state: "Jammu and Kashmir"),
    District(name: "Kathua", code: "KA", state: "Jammu and Kashmir"),
    District(name: "Kishtwar", code: "KI", state: "Jammu and Kashmir"),
    District(name: "Kulgam", code: "KU", state: "Jammu and Kashmir"),
    District(name: "Kupwara", code: "KU", state: "Jammu and Kashmir"),
    District(name: "Poonch", code: "PO", state: "Jammu and Kashmir"),
    District(name: "Pulwama", code: "PU", state: "Jammu and Kashmir"),
    District(name: "Rajouri", code: "RA", state: "Jammu and Kashmir"),
    District(name: "Ramban", code: "RA", state: "Jammu and Kashmir"),
    District(name: "Reasi", code: "RE", state: "Jammu and Kashmir"),
    District(name: "Samba", code: "SA", state: "Jammu and Kashmir"),
    District(name: "Shopian", code: "SH", state: "Jammu and Kashmir"),
    District(name: "Srinagar", code: "SR", state: "Jammu and Kashmir"),
    District(name: "Udhampur", code: "UD", state: "Jammu and Kashmir"),

    // Jharkhand
    District(name: "Bokaro", code: "BO", state: "Jharkhand"),
    District(name: "Chatra", code: "CH", state: "Jharkhand"),
    District(name: "Deoghar", code: "DE", state: "Jharkhand"),
    District(name: "Dhanbad", code: "DH", state: "Jharkhand"),
    District(name: "Dumka", code: "DU", state: "Jharkhand"),
    District(name: "East Singhbhum", code: "ES", state: "Jharkhand"),
    District(name: "Garhwa", code: "GA", state: "Jharkhand"),
    District(name: "Giridih", code: "GI", state: "Jharkhand"),
    District(name: "Godda", code: "GO", state: "Jharkhand"),
    District(name: "Gumla", code: "GU", state: "Jharkhand"),
    District(name: "Hazaribagh", code: "HA", state: "Jharkhand"),
    District(name: "Jamtara", code: "JA", state: "Jharkhand"),
    District(name: "Khunti", code: "KH", state: "Jharkhand"),
    District(name: "Koderma", code: "KO", state: "Jharkhand"),
    District(name: "Latehar", code: "LA", state: "Jharkhand"),
    District(name: "Lohardaga", code: "LO", state: "Jharkhand"),
    District(name: "Pakur", code: "PA", state: "Jharkhand"),
    District(name: "Palamu", code: "PA", state: "Jharkhand"),
    District(name: "Ramgarh", code: "RA", state: "Jharkhand"),
    District(name: "Ranchi", code: "RA", state: "Jharkhand"),
    District(name: "Sahebganj", code: "SA", state: "Jharkhand"),
    District(name: "Seraikela Kharsawan", code: "SK", state: "Jharkhand"),
    District(name: "Simdega", code: "SI", state: "Jharkhand"),
    District(name: "West Singhbhum", code: "WS", state: "Jharkhand"),

    // Karnataka
    District(name: "Bagalkot", code: "BA", state: "Karnataka"),
    District(name: "Bangalore Rural", code: "BR", state: "Karnataka"),
    District(name: "Bangalore Urban", code: "BU", state: "Karnataka"),
    District(name: "Belagavi", code: "BE", state: "Karnataka"),
    District(name: "Ballari", code: "BA", state: "Karnataka"),
    District(name: "Bidar", code: "BI", state: "Karnataka"),
    District(name: "Chamarajanagar", code: "CH", state: "Karnataka"),
    District(name: "Chikballapur", code: "CB", state: "Karnataka"),
    District(name: "Chikkamagaluru", code: "CM", state: "Karnataka"),
    District(name: "Chitradurga", code: "CH", state: "Karnataka"),
    District(name: "Dakshina Kannada", code: "DK", state: "Karnataka"),
    District(name: "Davanagere", code: "DA", state: "Karnataka"),
    District(name: "Dharwad", code: "DH", state: "Karnataka"),
    District(name: "Gadag", code: "GA", state: "Karnataka"),
    District(name: "Hassan", code: "HA", state: "Karnataka"),
    District(name: "Haveri", code: "HA", state: "Karnataka"),
    District(name: "Kalaburagi", code: "KA", state: "Karnataka"),
    District(name: "Kodagu", code: "KO", state: "Karnataka"),
    District(name: "Kolar", code: "KO", state: "Karnataka"),
    District(name: "Koppal", code: "KO", state: "Karnataka"),
    District(name: "Mandya", code: "MA", state: "Karnataka"),
    District(name: "Mysuru", code: "MY", state: "Karnataka"),
    District(name: "Raichur", code: "RA", state: "Karnataka"),
    District(name: "Ramanagara", code: "RA", state: "Karnataka"),
    District(name: "Shivamogga", code: "SH", state: "Karnataka"),
    District(name: "Tumakuru", code: "TU", state: "Karnataka"),
    District(name: "Udupi", code: "UD", state: "Karnataka"),
    District(name: "Uttara Kannada", code: "UK", state: "Karnataka"),
    District(name: "Vijayapura", code: "VI", state: "Karnataka"),
    District(name: "Yadgir", code: "YA", state: "Karnataka"),

    // Kerala
    District(name: "Alappuzha", code: "AL", state: "Kerala"),
    District(name: "Ernakulam", code: "ER", state: "Kerala"),
    District(name: "Idukki", code: "ID", state: "Kerala"),
    District(name: "Kannur", code: "KA", state: "Kerala"),
    District(name: "Kasaragod", code: "KA", state: "Kerala"),
    District(name: "Kollam", code: "KO", state: "Kerala"),
    District(name: "Kottayam", code: "KO", state: "Kerala"),
    District(name: "Kozhikode", code: "KO", state: "Kerala"),
    District(name: "Malappuram", code: "MA", state: "Kerala"),
    District(name: "Palakkad", code: "PA", state: "Kerala"),
    District(name: "Pathanamthitta", code: "PA", state: "Kerala"),
    District(name: "Thiruvananthapuram", code: "TH", state: "Kerala"),
    District(name: "Thrissur", code: "TH", state: "Kerala"),
    District(name: "Wayanad", code: "WA", state: "Kerala"),

    // Madhya Pradesh
    District(name: "Agar Malwa", code: "AM", state: "Madhya Pradesh"),
    District(name: "Alirajpur", code: "AL", state: "Madhya Pradesh"),
    District(name: "Anuppur", code: "AN", state: "Madhya Pradesh"),
    District(name: "Ashoknagar", code: "AS", state: "Madhya Pradesh"),
    District(name: "Balaghat", code: "BA", state: "Madhya Pradesh"),
    District(name: "Barwani", code: "BA", state: "Madhya Pradesh"),
    District(name: "Betul", code: "BE", state: "Madhya Pradesh"),
    District(name: "Bhind", code: "BH", state: "Madhya Pradesh"),
    District(name: "Bhopal", code: "BH", state: "Madhya Pradesh"),
    District(name: "Burhanpur", code: "BU", state: "Madhya Pradesh"),
    District(name: "Chachaura", code: "CH", state: "Madhya Pradesh"),
    District(name: "Chhatarpur", code: "CH", state: "Madhya Pradesh"),
    District(name: "Chhindwara", code: "CH", state: "Madhya Pradesh"),
    District(name: "Damoh", code: "DA", state: "Madhya Pradesh"),
    District(name: "Datia", code: "DA", state: "Madhya Pradesh"),
    District(name: "Dewas", code: "DE", state: "Madhya Pradesh"),
    District(name: "Dhar", code: "DH", state: "Madhya Pradesh"),
    District(name: "Dindori", code: "DI", state: "Madhya Pradesh"),
    District(name: "Guna", code: "GU", state: "Madhya Pradesh"),
    District(name: "Gwalior", code: "GW", state: "Madhya Pradesh"),
    District(name: "Harda", code: "HA", state: "Madhya Pradesh"),
    District(name: "Hoshangabad", code: "HO", state: "Madhya Pradesh"),
    District(name: "Indore", code: "IN", state: "Madhya Pradesh"),
    District(name: "Jabalpur", code: "JA", state: "Madhya Pradesh"),
    District(name: "Jhabua", code: "JH", state: "Madhya Pradesh"),
    District(name: "Katni", code: "KA", state: "Madhya Pradesh"),
    District(name: "Khandwa", code: "KH", state: "Madhya Pradesh"),
    District(name: "Khargone", code: "KH", state: "Madhya Pradesh"),
    District(name: "Mandla", code: "MA", state: "Madhya Pradesh"),
    District(name: "Mandsaur", code: "MA", state: "Madhya Pradesh"),
    District(name: "Morena", code: "MO", state: "Madhya Pradesh"),
    District(name: "Narsinghpur", code: "NA", state: "Madhya Pradesh"),
    District(name: "Neemuch", code: "NE", state: "Madhya Pradesh"),
    District(name: "Niwari", code: "NI", state: "Madhya Pradesh"),
    District(name: "Panna", code: "PA", state: "Madhya Pradesh"),
    District(name: "Raisen", code: "RA", state: "Madhya Pradesh"),
    District(name: "Rajgarh", code: "RA", state: "Madhya Pradesh"),
    District(name: "Ratlam", code: "RA", state: "Madhya Pradesh"),
    District(name: "Rewa", code: "RE", state: "Madhya Pradesh"),
    District(name: "Sagar", code: "SA", state: "Madhya Pradesh"),
    District(name: "Satna", code: "SA", state: "Madhya Pradesh"),
    District(name: "Sehore", code: "SE", state: "Madhya Pradesh"),
    District(name: "Seoni", code: "SE", state: "Madhya Pradesh"),
    District(name: "Shahdol", code: "SH", state: "Madhya Pradesh"),
    District(name: "Shajapur", code: "SH", state: "Madhya Pradesh"),
    District(name: "Sheopur", code: "SH", state: "Madhya Pradesh"),
    District(name: "Shivpuri", code: "SH", state: "Madhya Pradesh"),
    District(name: "Sidhi", code: "SI", state: "Madhya Pradesh"),
    District(name: "Singrauli", code: "SI", state: "Madhya Pradesh"),
    District(name: "Tikamgarh", code: "TI", state: "Madhya Pradesh"),
    District(name: "Ujjain", code: "UJ", state: "Madhya Pradesh"),
    District(name: "Umaria", code: "UM", state: "Madhya Pradesh"),
    District(name: "Vidisha", code: "VI", state: "Madhya Pradesh"),

    // Maharashtra
    District(name: "Ahmednagar", code: "AH", state: "Maharashtra"),
    District(name: "Akola", code: "AK", state: "Maharashtra"),
    District(name: "Amravati", code: "AM", state: "Maharashtra"),
    District(name: "Aurangabad", code: "AU", state: "Maharashtra"),
    District(name: "Beed", code: "BE", state: "Maharashtra"),
    District(name: "Bhandara", code: "BH", state: "Maharashtra"),
    District(name: "Buldhana", code: "BU", state: "Maharashtra"),
    District(name: "Chandrapur", code: "CH", state: "Maharashtra"),
    District(name: "Dhule", code: "DH", state: "Maharashtra"),
    District(name: "Gadchiroli", code: "GA", state: "Maharashtra"),
    District(name: "Gondia", code: "GO", state: "Maharashtra"),
    District(name: "Hingoli", code: "HI", state: "Maharashtra"),
    District(name: "Jalgaon", code: "JA", state: "Maharashtra"),
    District(name: "Jalna", code: "JA", state: "Maharashtra"),
    District(name: "Kolhapur", code: "KO", state: "Maharashtra"),
    District(name: "Latur", code: "LA", state: "Maharashtra"),
    District(name: "Mumbai City", code: "MC", state: "Maharashtra"),
    District(name: "Mumbai Suburban", code: "MS", state: "Maharashtra"),
    District(name: "Nagpur", code: "NA", state: "Maharashtra"),
    District(name: "Nanded", code: "NA", state: "Maharashtra"),
    District(name: "Nandurbar", code: "NA", state: "Maharashtra"),
    District(name: "Nashik", code: "NA", state: "Maharashtra"),
    District(name: "Osmanabad", code: "OS", state: "Maharashtra"),
    District(name: "Palghar", code: "PA", state: "Maharashtra"),
    District(name: "Parbhani", code: "PA", state: "Maharashtra"),
    District(name: "Pune", code: "PU", state: "Maharashtra"),
    District(name: "Raigad", code: "RA", state: "Maharashtra"),
    District(name: "Ratnagiri", code: "RA", state: "Maharashtra"),
    District(name: "Sangli", code: "SA", state: "Maharashtra"),
    District(name: "Satara", code: "SA", state: "Maharashtra"),
    District(name: "Sindhudurg", code: "SI", state: "Maharashtra"),
    District(name: "Solapur", code: "SO", state: "Maharashtra"),
    District(name: "Thane", code: "TH", state: "Maharashtra"),
    District(name: "Wardha", code: "WA", state: "Maharashtra"),
    District(name: "Washim", code: "WA", state: "Maharashtra"),
    District(name: "Yavatmal", code: "YA", state: "Maharashtra"),

    // Manipur
    District(name: "Bishnupur", code: "BI", state: "Manipur"),
    District(name: "Chandel", code: "CH", state: "Manipur"),
    District(name: "Churachandpur", code: "CH", state: "Manipur"),
    District(name: "Imphal East", code: "IE", state: "Manipur"),
    District(name: "Imphal West", code: "IW", state: "Manipur"),
    District(name: "Jiribam", code: "JI", state: "Manipur"),
    District(name: "Kakching", code: "KA", state: "Manipur"),
    District(name: "Kamjong", code: "KA", state: "Manipur"),
    District(name: "Kangpokpi", code: "KA", state: "Manipur"),
    District(name: "Noney", code: "NO", state: "Manipur"),
    District(name: "Pherzawl", code: "PH", state: "Manipur"),
    District(name: "Senapati", code: "SE", state: "Manipur"),
    District(name: "Tamenglong", code: "TA", state: "Manipur"),
    District(name: "Tengnoupal", code: "TE", state: "Manipur"),
    District(name: "Thoubal", code: "TH", state: "Manipur"),
    District(name: "Ukhrul", code: "UK", state: "Manipur"),

    // Meghalaya
    District(name: "East Garo Hills", code: "EG", state: "Meghalaya"),
    District(name: "East Jaintia Hills", code: "EJ", state: "Meghalaya"),
    District(name: "East Khasi Hills", code: "EK", state: "Meghalaya"),
    District(name: "North Garo Hills", code: "NG", state: "Meghalaya"),
    District(name: "Ri Bhoi", code: "RB", state: "Meghalaya"),
    District(name: "South Garo Hills", code: "SG", state: "Meghalaya"),
    District(name: "South West Garo Hills", code: "SW", state: "Meghalaya"),
    District(name: "South West Khasi Hills", code: "SK", state: "Meghalaya"),
    District(name: "West Garo Hills", code: "WG", state: "Meghalaya"),
    District(name: "West Jaintia Hills", code: "WJ", state: "Meghalaya"),
    District(name: "West Khasi Hills", code: "WK", state: "Meghalaya"),

    // Mizoram
    District(name: "Aizawl", code: "AI", state: "Mizoram"),
    District(name: "Champhai", code: "CH", state: "Mizoram"),
    District(name: "Hnahthial", code: "HN", state: "Mizoram"),
    District(name: "Khawzawl", code: "KH", state: "Mizoram"),
    District(name: "Kolasib", code: "KO", state: "Mizoram"),
    District(name: "Lawngtlai", code: "LA", state: "Mizoram"),
    District(name: "Lunglei", code: "LU", state: "Mizoram"),
    District(name: "Mamit", code: "MA", state: "Mizoram"),
    District(name: "Saiha", code: "SA", state: "Mizoram"),
    District(name: "Saitual", code: "SI", state: "Mizoram"),
    District(name: "Serchhip", code: "SE", state: "Mizoram"),

    // Nagaland
    District(name: "Dimapur", code: "DI", state: "Nagaland"),
    District(name: "Kiphire", code: "KI", state: "Nagaland"),
    District(name: "Kohima", code: "KO", state: "Nagaland"),
    District(name: "Longleng", code: "LO", state: "Nagaland"),
    District(name: "Mokokchung", code: "MO", state: "Nagaland"),
    District(name: "Mon", code: "MO", state: "Nagaland"),
    District(name: "Noklak", code: "NO", state: "Nagaland"),
    District(name: "Peren", code: "PE", state: "Nagaland"),
    District(name: "Phek", code: "PH", state: "Nagaland"),
    District(name: "Tuensang", code: "TU", state: "Nagaland"),
    District(name: "Wokha", code: "WO", state: "Nagaland"),
    District(name: "Zunheboto", code: "ZU", state: "Nagaland"),

    // Odisha
    District(name: "Angul", code: "AN", state: "Odisha"),
    District(name: "Balangir", code: "BA", state: "Odisha"),
    District(name: "Balasore", code: "BA", state: "Odisha"),
    District(name: "Bargarh", code: "BA", state: "Odisha"),
    District(name: "Bhadrak", code: "BH", state: "Odisha"),
    District(name: "Boudh", code: "BO", state: "Odisha"),
    District(name: "Cuttack", code: "CU", state: "Odisha"),
    District(name: "Deogarh", code: "DE", state: "Odisha"),
    District(name: "Dhenkanal", code: "DH", state: "Odisha"),
    District(name: "Gajapati", code: "GA", state: "Odisha"),
    District(name: "Ganjam", code: "GA", state: "Odisha"),
    District(name: "Jagatsinghpur", code: "JA", state: "Odisha"),
    District(name: "Jajpur", code: "JA", state: "Odisha"),
    District(name: "Jharsuguda", code: "JH", state: "Odisha"),
    District(name: "Kalahandi", code: "KA", state: "Odisha"),
    District(name: "Kandhamal", code: "KA", state: "Odisha"),
    District(name: "Kendrapara", code: "KE", state: "Odisha"),
    District(name: "Kendujhar", code: "KE", state: "Odisha"),
    District(name: "Khordha", code: "KH", state: "Odisha"),
    District(name: "Koraput", code: "KO", state: "Odisha"),
    District(name: "Malkangiri", code: "MA", state: "Odisha"),
    District(name: "Mayurbhanj", code: "MA", state: "Odisha"),
    District(name: "Nabarangpur", code: "NA", state: "Odisha"),
    District(name: "Nayagarh", code: "NA", state: "Odisha"),
    District(name: "Nuapada", code: "NU", state: "Odisha"),
    District(name: "Puri", code: "PU", state: "Odisha"),
    District(name: "Rayagada", code: "RA", state: "Odisha"),
    District(name: "Sambalpur", code: "SA", state: "Odisha"),
    District(name: "Subarnapur", code: "SU", state: "Odisha"),
    District(name: "Sundargarh", code: "SU", state: "Odisha"),

    // Punjab
    District(name: "Amritsar", code: "AM", state: "Punjab"),
    District(name: "Barnala", code: "BA", state: "Punjab"),
    District(name: "Bathinda", code: "BA", state: "Punjab"),
    District(name: "Faridkot", code: "FA", state: "Punjab"),
    District(name: "Fatehgarh Sahib", code: "FA", state: "Punjab"),
    District(name: "Fazilka", code: "FA", state: "Punjab"),
    District(name: "Ferozepur", code: "FE", state: "Punjab"),
    District(name: "Gurdaspur", code: "GU", state: "Punjab"),
    District(name: "Hoshiarpur", code: "HO", state: "Punjab"),
    District(name: "Jalandhar", code: "JA", state: "Punjab"),
    District(name: "Kapurthala", code: "KA", state: "Punjab"),
    District(name: "Ludhiana", code: "LU", state: "Punjab"),
    District(name: "Mansa", code: "MA", state: "Punjab"),
    District(name: "Moga", code: "MO", state: "Punjab"),
    District(name: "Mohali", code: "MO", state: "Punjab"),
    District(name: "Muktsar", code: "MU", state: "Punjab"),
    District(name: "Nawanshahr", code: "NA", state: "Punjab"),
    District(name: "Pathankot", code: "PA", state: "Punjab"),
    District(name: "Patiala", code: "PA", state: "Punjab"),
    District(name: "Rupnagar", code: "RU", state: "Punjab"),
    District(name: "Sangrur", code: "SA", state: "Punjab"),
    District(name: "Tarn Taran", code: "TA", state: "Punjab"),

    // Rajasthan
    District(name: "Ajmer", code: "AJ", state: "Rajasthan"),
    District(name: "Alwar", code: "AL", state: "Rajasthan"),
    District(name: "Banswara", code: "BA", state: "Rajasthan"),
    District(name: "Baran", code: "BA", state: "Rajasthan"),
    District(name: "Barmer", code: "BA", state: "Rajasthan"),
    District(name: "Bharatpur", code: "BH", state: "Rajasthan"),
    District(name: "Bhilwara", code: "BH", state: "Rajasthan"),
    District(name: "Bikaner", code: "BI", state: "Rajasthan"),
    District(name: "Bundi", code: "BU", state: "Rajasthan"),
    District(name: "Chittorgarh", code: "CH", state: "Rajasthan"),
    District(name: "Churu", code: "CH", state: "Rajasthan"),
    District(name: "Dausa", code: "DA", state: "Rajasthan"),
    District(name: "Dholpur", code: "DH", state: "Rajasthan"),
    District(name: "Dungarpur", code: "DU", state: "Rajasthan"),
    District(name: "Hanumangarh", code: "HA", state: "Rajasthan"),
    District(name: "Jaipur", code: "JA", state: "Rajasthan"),
    District(name: "Jaisalmer", code: "JA", state: "Rajasthan"),
    District(name: "Jalore", code: "JA", state: "Rajasthan"),
    District(name: "Jhalawar", code: "JH", state: "Rajasthan"),
    District(name: "Jhunjhunu", code: "JH", state: "Rajasthan"),
    District(name: "Jodhpur", code: "JO", state: "Rajasthan"),
    District(name: "Karauli", code: "KA", state: "Rajasthan"),
    District(name: "Kota", code: "KO", state: "Rajasthan"),
    District(name: "Nagaur", code: "NA", state: "Rajasthan"),
    District(name: "Pali", code: "PA", state: "Rajasthan"),
    District(name: "Pratapgarh", code: "PR", state: "Rajasthan"),
    District(name: "Rajsamand", code: "RA", state: "Rajasthan"),
    District(name: "Sawai Madhopur", code: "SA", state: "Rajasthan"),
    District(name: "Sikar", code: "SI", state: "Rajasthan"),
    District(name: "Sirohi", code: "SI", state: "Rajasthan"),
    District(name: "Sri Ganganagar", code: "SG", state: "Rajasthan"),
    District(name: "Tonk", code: "TO", state: "Rajasthan"),
    District(name: "Udaipur", code: "UD", state: "Rajasthan"),

    // Sikkim
    District(name: "East Sikkim", code: "ES", state: "Sikkim"),
    District(name: "North Sikkim", code: "NS", state: "Sikkim"),
    District(name: "South Sikkim", code: "SS", state: "Sikkim"),
    District(name: "West Sikkim", code: "WS", state: "Sikkim"),

    // Tamil Nadu
    District(name: "Ariyalur", code: "AR", state: "Tamil Nadu"),
    District(name: "Chengalpattu", code: "CH", state: "Tamil Nadu"),
    District(name: "Chennai", code: "CH", state: "Tamil Nadu"),
    District(name: "Coimbatore", code: "CO", state: "Tamil Nadu"),
    District(name: "Cuddalore", code: "CU", state: "Tamil Nadu"),
    District(name: "Dharmapuri", code: "DH", state: "Tamil Nadu"),
    District(name: "Dindigul", code: "DI", state: "Tamil Nadu"),
    District(name: "Erode", code: "ER", state: "Tamil Nadu"),
    District(name: "Kallakurichi", code: "KA", state: "Tamil Nadu"),
    District(name: "Kanchipuram", code: "KA", state: "Tamil Nadu"),
    District(name: "Kanyakumari", code: "KA", state: "Tamil Nadu"),
    District(name: "Karur", code: "KA", state: "Tamil Nadu"),
    District(name: "Krishnagiri", code: "KR", state: "Tamil Nadu"),
    District(name: "Madurai", code: "MA", state: "Tamil Nadu"),
    District(name: "Nagapattinam", code: "NA", state: "Tamil Nadu"),
    District(name: "Namakkal", code: "NA", state: "Tamil Nadu"),
    District(name: "Nilgiris", code: "NI", state: "Tamil Nadu"),
    District(name: "Perambalur", code: "PE", state: "Tamil Nadu"),
    District(name: "Pudukkottai", code: "PU", state: "Tamil Nadu"),
    District(name: "Ramanathapuram", code: "RA", state: "Tamil Nadu"),
    District(name: "Ranipet", code: "RA", state: "Tamil Nadu"),
    District(name: "Salem", code: "SA", state: "Tamil Nadu"),
    District(name: "Sivaganga", code: "SI", state: "Tamil Nadu"),
    District(name: "Tenkasi", code: "TE", state: "Tamil Nadu"),
    District(name: "Thanjavur", code: "TH", state: "Tamil Nadu"),
    District(name: "Theni", code: "TH", state: "Tamil Nadu"),
    District(name: "Thoothukudi", code: "TH", state: "Tamil Nadu"),
    District(name: "Tiruchirappalli", code: "TI", state: "Tamil Nadu"),
    District(name: "Tirunelveli", code: "TI", state: "Tamil Nadu"),
    District(name: "Tirupathur", code: "TI", state: "Tamil Nadu"),
    District(name: "Tiruppur", code: "TI", state: "Tamil Nadu"),
    District(name: "Tiruvallur", code: "TI", state: "Tamil Nadu"),
    District(name: "Tiruvannamalai", code: "TI", state: "Tamil Nadu"),
    District(name: "Tiruvarur", code: "TI", state: "Tamil Nadu"),
    District(name: "Vellore", code: "VE", state: "Tamil Nadu"),
    District(name: "Viluppuram", code: "VI", state: "Tamil Nadu"),
    District(name: "Virudhunagar", code: "VI", state: "Tamil Nadu"),

    // Telangana
    District(name: "Adilabad", code: "AD", state: "Telangana"),
    District(name: "Bhadradri Kothagudem", code: "BK", state: "Telangana"),
    District(name: "Hyderabad", code: "HY", state: "Telangana"),
    District(name: "Jagtial", code: "JA", state: "Telangana"),
    District(name: "Jangaon", code: "JA", state: "Telangana"),
    District(name: "Jayashankar Bhupalapally", code: "JB", state: "Telangana"),
    District(name: "Jogulamba Gadwal", code: "JG", state: "Telangana"),
    District(name: "Kamareddy", code: "KA", state: "Telangana"),
    District(name: "Karimnagar", code: "KA", state: "Telangana"),
    District(name: "Khammam", code: "KH", state: "Telangana"),
    District(name: "Komaram Bheem Asifabad", code: "KB", state: "Telangana"),
    District(name: "Mahabubabad", code: "MA", state: "Telangana"),
    District(name: "Mahbubnagar", code: "MA", state: "Telangana"),
    District(name: "Mancherial", code: "MA", state: "Telangana"),
    District(name: "Medak", code: "ME", state: "Telangana"),
    District(name: "Medchal-Malkajgiri", code: "MM", state: "Telangana"),
    District(name: "Mulugu", code: "MU", state: "Telangana"),
    District(name: "Nagarkurnool", code: "NA", state: "Telangana"),
    District(name: "Nalgonda", code: "NA", state: "Telangana"),
    District(name: "Narayanpet", code: "NA", state: "Telangana"),
    District(name: "Nirmal", code: "NI", state: "Telangana"),
    District(name: "Nizamabad", code: "NI", state: "Telangana"),
    District(name: "Peddapalli", code: "PE", state: "Telangana"),
    District(name: "Rajanna Sircilla", code: "RS", state: "Telangana"),
    District(name: "Ranga Reddy", code: "RR", state: "Telangana"),
    District(name: "Sangareddy", code: "SA", state: "Telangana"),
    District(name: "Siddipet", code: "SI", state: "Telangana"),
    District(name: "Suryapet", code: "SU", state: "Telangana"),
    District(name: "Vikarabad", code: "VI", state: "Telangana"),
    District(name: "Wanaparthy", code: "WA", state: "Telangana"),
    District(name: "Warangal Rural", code: "WR", state: "Telangana"),
    District(name: "Warangal Urban", code: "WU", state: "Telangana"),
    District(name: "Yadadri Bhuvanagiri", code: "YB", state: "Telangana"),

    // Tripura
    District(name: "Dhalai", code: "DH", state: "Tripura"),
    District(name: "Gomati", code: "GO", state: "Tripura"),
    District(name: "Khowai", code: "KH", state: "Tripura"),
    District(name: "North Tripura", code: "NT", state: "Tripura"),
    District(name: "Sepahijala", code: "SE", state: "Tripura"),
    District(name: "South Tripura", code: "ST", state: "Tripura"),
    District(name: "Unakoti", code: "UN", state: "Tripura"),
    District(name: "West Tripura", code: "WT", state: "Tripura"),

    // Uttar Pradesh
    District(name: "Agra", code: "AG", state: "Uttar Pradesh"),
    District(name: "Aligarh", code: "AL", state: "Uttar Pradesh"),
    District(name: "Ambedkar Nagar", code: "AN", state: "Uttar Pradesh"),
    District(name: "Amethi", code: "AM", state: "Uttar Pradesh"),
    District(name: "Amroha", code: "AM", state: "Uttar Pradesh"),
    District(name: "Auraiya", code: "AU", state: "Uttar Pradesh"),
    District(name: "Ayodhya", code: "AY", state: "Uttar Pradesh"),
    District(name: "Azamgarh", code: "AZ", state: "Uttar Pradesh"),
    District(name: "Badaun", code: "BA", state: "Uttar Pradesh"),
    District(name: "Baghpat", code: "BA", state: "Uttar Pradesh"),
    District(name: "Bahraich", code: "BA", state: "Uttar Pradesh"),
    District(name: "Ballia", code: "BA", state: "Uttar Pradesh"),
    District(name: "Balrampur", code: "BA", state: "Uttar Pradesh"),
    District(name: "Banda", code: "BA", state: "Uttar Pradesh"),
    District(name: "Barabanki", code: "BA", state: "Uttar Pradesh"),
    District(name: "Bareilly", code: "BA", state: "Uttar Pradesh"),
    District(name: "Basti", code: "BA", state: "Uttar Pradesh"),
    District(name: "Bhadohi", code: "BH", state: "Uttar Pradesh"),
    District(name: "Bijnor", code: "BI", state: "Uttar Pradesh"),
    District(name: "Bulandshahr", code: "BU", state: "Uttar Pradesh"),
    District(name: "Chandauli", code: "CH", state: "Uttar Pradesh"),
    District(name: "Chitrakoot", code: "CH", state: "Uttar Pradesh"),
    District(name: "Deoria", code: "DE", state: "Uttar Pradesh"),
    District(name: "Etah", code: "ET", state: "Uttar Pradesh"),
    District(name: "Etawah", code: "ET", state: "Uttar Pradesh"),
    District(name: "Farrukhabad", code: "FA", state: "Uttar Pradesh"),
    District(name: "Fatehpur", code: "FA", state: "Uttar Pradesh"),
    District(name: "Firozabad", code: "FI", state: "Uttar Pradesh"),
    District(name: "Gautam Buddha Nagar", code: "GA", state: "Uttar Pradesh"),
    District(name: "Ghaziabad", code: "GH", state: "Uttar Pradesh"),
    District(name: "Ghazipur", code: "GH", state: "Uttar Pradesh"),
    District(name: "Gonda", code: "GO", state: "Uttar Pradesh"),
    District(name: "Gorakhpur", code: "GO", state: "Uttar Pradesh"),
    District(name: "Hamirpur", code: "HA", state: "Uttar Pradesh"),
    District(name: "Hapur", code: "HA", state: "Uttar Pradesh"),
    District(name: "Hardoi", code: "HA", state: "Uttar Pradesh"),
    District(name: "Hathras", code: "HA", state: "Uttar Pradesh"),
    District(name: "Jalaun", code: "JA", state: "Uttar Pradesh"),
    District(name: "Jaunpur", code: "JA", state: "Uttar Pradesh"),
    District(name: "Jhansi", code: "JH", state: "Uttar Pradesh"),
    District(name: "Kannauj", code: "KA", state: "Uttar Pradesh"),
    District(name: "Kanpur Dehat", code: "KA", state: "Uttar Pradesh"),
    District(name: "Kanpur Nagar", code: "KA", state: "Uttar Pradesh"),
    District(name: "Kasganj", code: "KA", state: "Uttar Pradesh"),
    District(name: "Kaushambi", code: "KA", state: "Uttar Pradesh"),
    District(name: "Kushinagar", code: "KU", state: "Uttar Pradesh"),
    District(name: "Lakhimpur Kheri", code: "LA", state: "Uttar Pradesh"),
    District(name: "Lalitpur", code: "LA", state: "Uttar Pradesh"),
    District(name: "Lucknow", code: "LU", state: "Uttar Pradesh"),
    District(name: "Maharajganj", code: "MA", state: "Uttar Pradesh"),
    District(name: "Mahoba", code: "MA", state: "Uttar Pradesh"),
    District(name: "Mainpuri", code: "MA", state: "Uttar Pradesh"),
    District(name: "Mathura", code: "MA", state: "Uttar Pradesh"),
    District(name: "Mau", code: "MA", state: "Uttar Pradesh"),
    District(name: "Meerut", code: "ME", state: "Uttar Pradesh"),
    District(name: "Mirzapur", code: "MI", state: "Uttar Pradesh"),
    District(name: "Moradabad", code: "MO", state: "Uttar Pradesh"),
    District(name: "Muzaffarnagar", code: "MU", state: "Uttar Pradesh"),
    District(name: "Pilibhit", code: "PI", state: "Uttar Pradesh"),
    District(name: "Pratapgarh", code: "PR", state: "Uttar Pradesh"),
    District(name: "Raebareli", code: "RA", state: "Uttar Pradesh"),
    District(name: "Rampur", code: "RA", state: "Uttar Pradesh"),
    District(name: "Saharanpur", code: "SA", state: "Uttar Pradesh"),
    District(name: "Sambhal", code: "SA", state: "Uttar Pradesh"),
    District(name: "Sant Kabir Nagar", code: "SK", state: "Uttar Pradesh"),
    District(name: "Shahjahanpur", code: "SH", state: "Uttar Pradesh"),
    District(name: "Shamli", code: "SH", state: "Uttar Pradesh"),
    District(name: "Shrawasti", code: "SH", state: "Uttar Pradesh"),
    District(name: "Siddharthnagar", code: "SI", state: "Uttar Pradesh"),
    District(name: "Sitapur", code: "SI", state: "Uttar Pradesh"),
    District(name: "Sonbhadra", code: "SO", state: "Uttar Pradesh"),
    District(name: "Sultanpur", code: "SU", state: "Uttar Pradesh"),
    District(name: "Unnao", code: "UN", state: "Uttar Pradesh"),
    District(name: "Varanasi", code: "VA", state: "Uttar Pradesh"),

    // Uttarakhand
    District(name: "Almora", code: "AL", state: "Uttarakhand"),
    District(name: "Bageshwar", code: "BA", state: "Uttarakhand"),
    District(name: "Chamoli", code: "CH", state: "Uttarakhand"),
    District(name: "Champawat", code: "CH", state: "Uttarakhand"),
    District(name: "Dehradun", code: "DE", state: "Uttarakhand"),
    District(name: "Haridwar", code: "HA", state: "Uttarakhand"),
    District(name: "Nainital", code: "NA", state: "Uttarakhand"),
    District(name: "Pauri Garhwal", code: "PA", state: "Uttarakhand"),
    District(name: "Pithoragarh", code: "PI", state: "Uttarakhand"),
    District(name: "Rudraprayag", code: "RU", state: "Uttarakhand"),
    District(name: "Tehri Garhwal", code: "TE", state: "Uttarakhand"),
    District(name: "Udham Singh Nagar", code: "UD", state: "Uttarakhand"),
    District(name: "Uttarkashi", code: "UT", state: "Uttarakhand"),

    // West Bengal
    District(name: "Alipurduar", code: "AL", state: "West Bengal"),
    District(name: "Bankura", code: "BA", state: "West Bengal"),
    District(name: "Birbhum", code: "BI", state: "West Bengal"),
    District(name: "Cooch Behar", code: "CO", state: "West Bengal"),
    District(name: "Dakshin Dinajpur", code: "DA", state: "West Bengal"),
    District(name: "Darjeeling", code: "DA", state: "West Bengal"),
    District(name: "Hooghly", code: "HO", state: "West Bengal"),
    District(name: "Howrah", code: "HO", state: "West Bengal"),
    District(name: "Jalpaiguri", code: "JA", state: "West Bengal"),
    District(name: "Jhargram", code: "JH", state: "West Bengal"),
    District(name: "Kalimpong", code: "KA", state: "West Bengal"),
    District(name: "Kolkata", code: "KO", state: "West Bengal"),
    District(name: "Malda", code: "MA", state: "West Bengal"),
    District(name: "Murshidabad", code: "MU", state: "West Bengal"),
    District(name: "Nadia", code: "NA", state: "West Bengal"),
    District(name: "North 24 Parganas", code: "NO", state: "West Bengal"),
    District(name: "Paschim Bardhaman", code: "PA", state: "West Bengal"),
    District(name: "Paschim Medinipur", code: "PA", state: "West Bengal"),
    District(name: "Purba Bardhaman", code: "PU", state: "West Bengal"),
    District(name: "Purba Medinipur", code: "PU", state: "West Bengal"),
    District(name: "Purulia", code: "PU", state: "West Bengal"),
    District(name: "South 24 Parganas", code: "SO", state: "West Bengal"),
    District(name: "Uttar Dinajpur", code: "UT", state: "West Bengal"),

    // Andaman and Nicobar Islands
    District(name: "Nicobar", code: "NI", state: "Andaman and Nicobar Islands"),
    District(name: "North and Middle Andaman", code: "NO", state: "Andaman and Nicobar Islands"),
    District(name: "South Andaman", code: "SO", state: "Andaman and Nicobar Islands"),

    // Chandigarh
    District(name: "Chandigarh", code: "CH", state: "Chandigarh"),

    // Dadra and Nagar Haveli
    District(name: "Dadra and Nagar Haveli", code: "DA", state: "Dadra and Nagar Haveli"),

    // Daman and Diu
    District(name: "Daman", code: "DA", state: "Daman and Diu"),
    District(name: "Diu", code: "DI", state: "Daman and Diu"),

    // Delhi
    District(name: "Central Delhi", code: "CE", state: "Delhi"),
    District(name: "East Delhi", code: "EA", state: "Delhi"),
    District(name: "New Delhi", code: "NE", state: "Delhi"),
    District(name: "North Delhi", code: "NO", state: "Delhi"),
    District(name: "North East Delhi", code: "NE", state: "Delhi"),
    District(name: "North West Delhi", code: "NW", state: "Delhi"),
    District(name: "Shahdara", code: "SH", state: "Delhi"),
    District(name: "South Delhi", code: "SO", state: "Delhi"),
    District(name: "South East Delhi", code: "SE", state: "Delhi"),
    District(name: "South West Delhi", code: "SW", state: "Delhi"),
    District(name: "West Delhi", code: "WE", state: "Delhi"),

    // Lakshadweep
    District(name: "Agatti Island", code: "AG", state: "Lakshadweep"),
    District(name: "Amini", code: "AM", state: "Lakshadweep"),
    District(name: "Andrott", code: "AN", state: "Lakshadweep"),
    District(name: "Bitra", code: "BI", state: "Lakshadweep"),
    District(name: "Chetlat", code: "CH", state: "Lakshadweep"),
    District(name: "Kadmath", code: "KA", state: "Lakshadweep"),
    District(name: "Kalpeni", code: "KA", state: "Lakshadweep"),
    District(name: "Kavaratti", code: "KA", state: "Lakshadweep"),
    District(name: "Kiltan", code: "KI", state: "Lakshadweep"),
    District(name: "Minicoy", code: "MI", state: "Lakshadweep"),

  ];

  String getDateMonthFormat(String inputDate) {
    // Parse the input date string
    DateTime dateTime = DateTime.parse(inputDate.replaceAll('-', ''));

    // Format the date using the desired format
    String formattedDate = "${_getMonthAbbreviation(dateTime.month)} \n ${dateTime.day}";

    print(formattedDate); // Output: Oct \n 25

    return formattedDate;
  }

  String _getMonthAbbreviation(int month) {
    switch (month) {
      case 1:
        return 'Jan';
      case 2:
        return 'Feb';
      case 3:
        return 'Mar';
      case 4:
        return 'Apr';
      case 5:
        return 'May';
      case 6:
        return 'Jun';
      case 7:
        return 'Jul';
      case 8:
        return 'Aug';
      case 9:
        return 'Sep';
      case 10:
        return 'Oct';
      case 11:
        return 'Nov';
      case 12:
        return 'Dec';
      default:
        return '';
    }
  }


  String getDistrictCode(String districtName) {
    // Search for the district by name in the districts list
    District? district = districts.firstWhere(
          (element) => element.name == districtName,
      orElse: () => District(name: 'QQ', code: 'QQ',state: "QQ"), // Default value if district is not found
    );

    return district.code;
  }

  String getStateCode(String stateName) {
    // Search for the district by name in the districts list
    States? state = states.firstWhere(
          (element) => element.name == stateName,
      orElse: () => States(name: '', code: 'ZZ'), // Default value if district is not found
    );

    return state.code;
  }
}